load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(
    licenses = ["notice"],
)

################################################################################
# Array.
################################################################################
cc_test(
    name = "array_view_test",
    srcs = ["array_view_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# ClassLoader.
################################################################################
cc_test(
    name = "class_loader_ref_test",
    srcs = ["class_loader_ref_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation:configuration",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "class_loader_ref_second_test",
    srcs = ["class_loader_ref_second_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# Field.
################################################################################
cc_test(
    name = "field_ref_test",
    srcs = ["field_ref_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# GlobalObject.
################################################################################
cc_test(
    name = "global_object_test",
    srcs = ["global_object_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# JvmRef.
################################################################################
cc_test(
    name = "jvm_ref_test",
    srcs = ["jvm_ref_legacy_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# LocalArray.
################################################################################
cc_test(
    name = "local_array_field_multidimensional_test",
    srcs = ["local_array_field_multidimensional_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "local_array_field_test",
    srcs = ["local_array_field_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "local_array_iteration_test",
    srcs = ["local_array_iteration_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "local_array_multidimensional_test",
    srcs = ["local_array_multidimensional_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "local_array_method_test",
    srcs = ["local_array_method_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "local_array_method_multidimensional_test",
    srcs = ["local_array_method_multidimensional_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "local_array_string_test",
    srcs = ["local_array_string_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# LocalObject.
################################################################################
cc_test(
    name = "local_object_test",
    srcs = ["local_object_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# Method.
################################################################################
cc_test(
    name = "method_ref_test",
    srcs = ["method_ref_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# Multi type test.
################################################################################
cc_test(
    name = "multi_type_test",
    srcs = ["multi_type_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# Object.
################################################################################
cc_test(
    name = "overload_ref_test",
    srcs = ["overload_ref_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# Static.
################################################################################
cc_test(
    name = "static_ref_test",
    srcs = ["static_ref_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "string_ref_test",
    srcs = ["string_ref_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "//implementation/jni_helper:fake_test_constants",
        "@googletest//:gtest_main",
    ],
)

################################################################################
# Self.
################################################################################
cc_test(
    name = "self_test",
    srcs = ["self_test.cc"],
    deps = [
        "//:jni_bind",
        "//:jni_test",
        "@googletest//:gtest_main",
    ],
)
