load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "proto_helper",
    hdrs = ["proto_helper.h"],
    deps = [
        "@com_google_protobuf//:protobuf",
    ],
)
